// DO NOT MODIFY
//
// This file is automatically generated by the Firebase setup steps.

export const firebaseConfig = {
  apiKey: "AIzaSyA3gXBNiLdpJdTpOuTJt6UJs-yyHJqorgA",
  authDomain: "studio-9468926194-e03ac.firebaseapp.com",
  projectId: "studio-9468926194-e03ac",
  storageBucket: "studio-9468926194-e03ac.firebasestorage.app",
  messagingSenderId: "3344718739",
  appId: "1:3344718739:web:861d06325a5b518af1e666"
};
